### ISSUE TITLE
Thread-safety of MsgPackContext.GetConverter<T>

### ISSUE THREAD

**Issue by imb590** [roman-kozachenko/MsgPack.Light#77]
Since converters are stored in a `Dictionary` and there is no access synchronization, the method [`MsgPackContext.GetConverter<T>`](https://github.com/progaudi/MsgPack.Light/blob/1.5.0/src/msgpack.light/MsgPackContext.cs#L155) is not thread-safe. This becomes a problem when a converter is registered with `RegisterGenericConverter` like it is done [here](https://github.com/progaudi/progaudi.tarantool/blob/0.11.0/src/progaudi.tarantool/TarantoolConvertersRegistrator.cs#L43). The concrete generic types are becoming known to the serializer, who creates the converters with the non-thread-safe method, at the moment of serialization, and this may cause concurrent mutating `GetConverter<T>` calls.

So, as far as I understand, we must explicitly create the converters for all the concrete generic types and all the enums that may be serialized when creating `MsgPackContext`. This forces anyone who creates an `MsgPackContext` instance, for example the creator of `ProGaudi.Tarantool.Client.Box` in [places like this](https://github.com/progaudi/progaudi.tarantool/blob/0.11.0/samples/docker-compose/dotnet/Startup.cs#L33-L38), to be aware of every possible type that may be thrown at the serializer. This is quite inconvenient.

Why not switch to `ConcurrentDictionary` or synchronize access to `Dictionary` in `MsgPackContext` and get rid of this problem?

**Comment by justmara** [comment]
got smashed by this problem in tarantool connector today
```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at ProGaudi.MsgPack.Light.MsgPackContext.GetObjectActivator(Type type)
   at ProGaudi.MsgPack.Light.MsgPackContext.<>c__DisplayClass24_0.<TryGenerateConverterFromGenericConverter>b__0(Type x)
   at ProGaudi.MsgPack.Light.MsgPackContext.TryGenerateConverterFromGenericConverter(Type type)
   at ProGaudi.MsgPack.Light.MsgPackContext.GetConverter[T]()
   at ProGaudi.MsgPack.Light.MsgPackSerializer.GetConverter[T](MsgPackContext context)
   at ProGaudi.MsgPack.Light.MsgPackSerializer.Serialize[T](T data, MemoryStream stream, MsgPackContext context)
   at ProGaudi.Tarantool.Client.LogicalConnection.SendRequestImpl[TRequest](TRequest request, Nullable`1 timeout)
   at ProGaudi.Tarantool.Client.LogicalConnection.SendRequest[TRequest,TResponse](TRequest request, Nullable`1 timeout)
   at ProGaudi.Tarantool.Client.LogicalConnectionManager.SendRequest[TRequest,TResponse](TRequest request, Nullable`1 timeout)
   at ProGaudi.Tarantool.Client.Box.Call[TTuple,TResponse](String functionName, TTuple parameters)
```
